#! bin/bash
echo ECS_CLUSTER=${ClusterName} >> /etc/ecs/ecs.config
echo ECS_RESERVED_PORTS=[22, 2375, 2376, 51678, 51679] >> /etc/ecs/ecs.config
echo ECS_RESERVED_PORTS_UDP=[] >> /etc/ecs/ecs.config
echo DOCKER_HOST=unix:///var/run/docker.sock >> /etc/ecs/ecs.config
echo ECS_LOGLEVEL=info >> /etc/ecs/ecs.config
echo ECS_LOGLEVEL_ON_INSTANCE=info >> /etc/ecs/ecs.config
echo ECS_LOGFILE=/log/ecs-agent.log >> /etc/ecs/ecs.config
echo ECS_CHECKPOINT=true >> /etc/ecs/ecs.config
echo ECS_DATADIR=/data >> /etc/ecs/ecs.config
echo ECS_UPDATES_ENABLED=false >> /etc/ecs/ecs.config
echo ECS_DISABLE_METRICS=false >> /etc/ecs/ecs.config
echo ECS_POLL_METRICS=false >> /etc/ecs/ecs.config
echo ECS_POLLING_METRICS_WAIT_DURATION=10s >> /etc/ecs/ecs.config
echo ECS_PULL_DEPENDENT_CONTAINERS_UPFRONT=false >> /etc/ecs/ecs.config
echo ECS_RESERVED_MEMORY=0 >> /etc/ecs/ecs.config
echo ECS_AVAILABLE_LOGGING_DRIVERS=["json-file","awslogs"] >> /etc/ecs/ecs.config
echo ECS_DISABLE_PRIVILEGED=false >> /etc/ecs/ecs.config
echo ECS_SELINUX_CAPABLE=false >> /etc/ecs/ecs.config
echo ECS_APPARMOR_CAPABLE=false >> /etc/ecs/ecs.config
echo ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION=3h >> /etc/ecs/ecs.config
# echo ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION_JITTER= >> /etc/ecs/ecs.config
echo ECS_CONTAINER_STOP_TIMEOUT=30s >> /etc/ecs/ecs.config
echo ECS_CONTAINER_START_TIMEOUT=3m >> /etc/ecs/ecs.config
echo ECS_CONTAINER_CREATE_TIMEOUT=4m >> /etc/ecs/ecs.config
echo ECS_ENABLE_TASK_IAM_ROLE=true >> /etc/ecs/ecs.config
# echo ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST=true >> /etc/ecs/ecs.config
echo ECS_DISABLE_IMAGE_CLEANUP=false >> /etc/ecs/ecs.config
echo CREDENTIALS_FETCHER_HOST=unix:///var/credentials-fetcher/socket/credentials_fetcher.sock >> /etc/ecs/ecs.config