# To create a cluster using kind, run: `kind create cluster --name CLUSTER_NAME --config ~/Work/quick-reference/kubernetes/config/cluster/kind.yaml`
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraPortMappings:
    - containerPort: 32080
      hostPort: 32080
      listenAddress: "0.0.0.0"
      protocol: TCP