# EC2 Instance of type `t2.micro` running Ubuntu Server 22.04 with UserData script:
## - Update and Upgrade the server
## - Install AWS CLI v2
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  EC2WithUserData:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: ap-south-1a
      ImageId: ami-062df10d14676e201
      InstanceType: t2.micro
      KeyName: ec2-playground
      SecurityGroups:
        - launch-wizard-1
      UserData:
        Fn::Base64: |
          #! bin/bash
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install -y unzip
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          rm -rf ./aws awscliv2.zip
          sudo apt install -y nginx
          sudo sed -i "/<\/h1>/a <p>Hostname: $(hostname -f)</p>" /var/www/html/index.nginx-debian.html
